---
- name: Recolectar información del sistema
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Mostrar información del sistema desde facts
      debug:
        msg:
          - "Nombre del host: {{ ansible_hostname }}"
          - "Sistema operativo: {{ ansible_system }}"
          - "Distribución: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Arquitectura: {{ ansible_architecture }}"
          - "Número de CPUs: {{ ansible_processor_count }}"
          - "Número de CPUs lógicas: {{ ansible_processor_cores }}"
          - "Memoria total: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB"
          - "Memoria disponible: {{ (ansible_memfree_mb / 1024) | round(2) }} GB"

    - name: Obtener información del disco
      setup:
        filter: ansible_mounts
      register: disk_facts

    - name: Mostrar información de discos
      debug:
        msg: "Puntos de montaje: {{ disk_facts.ansible_facts.ansible_mounts | map(attribute='mount') | list }}"

    - name: Obtener espacio en disco con command (Linux)
      command: df -h /
      register: disk_usage
      changed_when: false
      ignore_errors: yes

    - name: Mostrar espacio en disco
      debug:
        msg: "Uso de disco (Linux): {{ disk_usage.stdout }}"
      when: disk_usage is succeeded

    - name: Verificar si es contenedor Docker
      command: grep -c docker /proc/self/cgroup
      register: is_docker
      changed_when: false
      ignore_errors: yes

    - name: Mostrar entorno de ejecución
      debug:
        msg: 
          - "Ejecutando en contenedor Docker: {{ is_docker.stdout | default('No determinado') }}"
          - "Es Linux: {{ ansible_system == 'Linux' }}"
          - "Kernel: {{ ansible_kernel }}"

    - name: Resumen del sistema
      debug:
        msg:
          - "=== RESUMEN DEL SISTEMA ==="
          - "Host: {{ ansible_hostname }}"
          - "SO: {{ ansible_system }} {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Arquitectura: {{ ansible_architecture }}"
          - "Kernel: {{ ansible_kernel }}"
          - "CPUs: {{ ansible_processor_count }} físicas, {{ ansible_processor_cores }} lógicas"
          - "Memoria: {{ (ansible_memtotal_mb / 1024) | round(2) }} GB"
          - "Docker: {{ is_docker.stdout | default('0') != '0' }}"
